server:
  port: 8081
#gif
gif:
  url: https://api.giphy.com/v1/gifs/random
  api_kay: VKcwC5rNwIqSznKEkm9FdoNHh0LrWq6P
  rich: rich
  broke: broke


#rate
course:
  utl: https://openexchangerates.org/api/
  app_id: 03a6c20a691540d4afea051b31578752
  rate:
    - AED
    - AFN
    - ALL
    - AMD
    - ANG
    - AOA
    - ARS
    - AUD
    - AWG
    - AZN
    - BAM
    - BBD
    - BDT
    - BGN
    - BHD
    - BIF
    - BMD
    - BND
    - BOB
    - BRL
    - BSD
    - BTC
    - BTN
    - BWP
    - BYN
    - BZD
    - CAD
    - CDF
    - CHF
    - CLF
    - CLP
    - CNH
    - CNY
    - COP
    - CRC
    - CUC
    - CUP
    - CVE
    - CZK
    - DJF
    - DKK
    - DOP
    - DZD
    - EGP
    - ERN
    - ETB
    - EUR
    - FJD
    - FKP
    - GBP
    - GEL
    - GGP
    - GHS
    - GIP
    - GMD
    - GNF
    - GTQ
    - GYD
    - HKD
    - HNL
    - HRK
    - HTG
    - HUF
    - IDR
    - ILS
    - IMP
    - INR
    - IQD
    - IRR
    - ISK
    - JEP
    - JMD
    - JOD
    - JPY
    - KES
    - KGS
    - KHR
    - KMF
    - KPW
    - KRW
    - KWD
    - KYD
    - KZT
    - LAK
    - LBP
    - LKR
    - LRD
    - LSL
    - LYD
    - MAD
    - MDL
    - MGA
    - MKD
    - MMK
    - MNT
    - MOP
    - MRU
    - MUR
    - MVR
    - MWK
    - MXN
    - MYR
    - MZN
    - NAD
    - NGN
    - NIO
    - NOK
    - NPR
    - NZD
    - OMR
    - PAB
    - PEN
    - PGK
    - PHP
    - PKR
    - PLN
    - PYG
    - QAR
    - RON
    - RSD
    - RUB
    - RWF
    - SAR
    - SBD
    - SCR
    - SDG
    - SEK
    - SGD
    - SHP
    - SLL
    - SOS
    - SRD
    - SSP
    - STD
    - STN
    - SVC
    - SYP
    - SZL
    - THB
    - TJS
    - TMT
    - TND
    - TOP
    - TRY
    - TTD
    - TWD
    - TZS
    - UAH
    - UGX
    - USD
    - UYU
    - UZS
    - VES
    - VND
    - VUV
    - WST
    - XAF
    - XAG
    - XAU
    - XCD
    - XDR
    - XOF
    - XPD
    - XPF
    - XPT
    - YER
    - ZAR
    - ZMW
    - ZWL